version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pg_jd_demo
    restart: unless-stopped
    environment:
      POSTGRES_USER: jd_user
      POSTGRES_PASSWORD: jd_pass
      POSTGRES_DB: jd_library
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: etcd_jd_demo
    restart: unless-stopped
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    volumes:
      - etcd_data:/etcd

  minio:
    image: minio/minio:latest
    container_name: minio_jd_demo
    command: server /data --console-address ":9001"
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    platform: linux/amd64
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Web Console UI
    volumes:
      - minio_data:/data

  milvus:
    image: milvusdb/milvus:v2.3.4
    container_name: milvus_jd_demo
    restart: unless-stopped
    platform: linux/amd64
    command: ["milvus", "run", "standalone"]
    ports:
      - "19530:19530"   # gRPC
      - "9091:9091"     # REST
    environment:
      TZ: UTC
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - milvus_data:/var/lib/milvus
    depends_on:
      - etcd
      - minio

volumes:
  pg_data:
  minio_data:
  milvus_data:
  etcd_data: