CREATE TABLE IF NOT EXISTS job_descriptions (
  jd_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_code        VARCHAR(50) UNIQUE NOT NULL,
  title           TEXT NOT NULL,
  department      TEXT,
  family_id       INTEGER REFERENCES job_families(family_id),
  level           VARCHAR(20),
  employment_type VARCHAR(20),
  location        TEXT,
  content_md      TEXT NOT NULL,
  version         INTEGER NOT NULL DEFAULT 1,
  created_by      VARCHAR(50),
  created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_job_desc_family ON job_descriptions(family_id);